version: '3.7'
services:
  spring:
    image: openjdk:8-jre-alpine
    container_name: roulette
    volumes:
      - .:/ruleta 
    environment: 
      - PORT:8080
    ports:
      - 8080:8080
    working_dir: /    
    depends_on:
      - redis
    command: sh -c 'cd ruleta;./mvnw spring-boot:run'  
  redis:
    container_name: roulette-redis
    image: redis:latest
    ports:
    - 6379:6379
    command:
    - redis-server
    - --appendonly
    - 'yes'
    volumes:
    - .:/data